<?php
//inputのnameとその名称設定
//'name'=>'名称'で１セット。一番最後には,をつけない。
//ここで書いた並び順が、確認画面と送信メール本文に反映される。
$inputs = array(
	'chk'=>'同意',
	'name1'=>'氏名',
	'name2'=>'ふりがな',
	'Work'=>'職業',
	'company'=>'施設名／会社名',
	'zipcode'=>'郵便番号',
	'pref'=>'都道府県',
	'address'=>'市区町村',
	'tel'=>'電話番号',
	'fax'=>'FAX番号',
	'email'=>'E-Mail',
	'message'=>'お問い合わせ内容'
);
?>